name: CI con documentación automática mediante JavaDoc

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

  

permissions:
  contents: write 


jobs:
  documentar:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Madrid
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
