name: CI con documentación automática mediante Doxygen

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

  

permissions:
  contents: write 


jobs:
  auto-doc:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Madrid
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configurar java
        uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: '21'
      - name: Crear el Doxyfile
        run: |
            cat > Doxyfile <<EOF
            PROJECT_NAME           = "Proyecto"
            OUTPUT_DIRECTORY       = docs
            INPUT                  = ./src
            FILE_PATTERNS          = *.java
            RECURSIVE              = YES
            GENERATE_HTML          = YES
            GENERATE_LATEX         = YES
            EOF

      - name: Documentar con doxygen en formato HTML y LATEX
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: ./Doxyfile

      - name: Commit automático de la documentación
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Documentación actualizada."


        
