name: CI con AutoCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *"

  

permissions:
  contents: write   # 👈 IMPORTANTE: permite que el bot pueda hacer commits/push
  issues: write  # Lo mismo pero para que pueda hacer issues


jobs:
  test-and-update:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Madrid
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name: Commit automático del README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README con estado de tests"
          file_pattern: README.md
  
  issue-on-fail:
    needs: test-and-update
    if: failure()  
    runs-on: ubuntu-latest
    steps:
      - name: Issue automático al fallar los tests
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "❌ Tests fallidos",
              body: "Se han detectado errores en los tests. Revisa el último commit."
            })
        
